'\" t
.\"     Title: rcs-fast-import
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/24/2010
.\"    Manual: Development Tools
.\"    Source: rcs-fast-import
.\"  Language: English
.\"
.TH "RCS\-FAST\-IMPORT" "1" "11/24/2010" "rcs\-fast\-import" "Development Tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rcs-fast-import \- unpack a fast\-import stream into an RCS repository tree
.SH "SYNOPSIS"
.HP \w'\fBrcs\-fast\-import\fR\ 'u
\fBrcs\-fast\-import\fR [\-v] [\-u] [\-l] [\-p] [\-V] [\-?]
.SH "DESCRIPTION"
.PP
This tool breaks the content of a git\-fast\-import stream on stdin into individual RCS master files in RCS subdirectories of the corresponding directory structure\&.
.PP
Normally, all import\-stream per\-commit metadata that RCS cannot represent natively is written into each comment as RFC\-822 mail headers, followed by a blank line; this includes mark, committer and author data, mark cross\-references to parent commits, and extension properties\&. The \-p option suppresses this, producing a plain RCS comment\&.
.PP
With the \-v option, emit a twirling\-baton prompt during stream read and do not suppress progess messages from the RCS tools\&.
.PP
With the \-l option, check out and lock all resulting files at their latest revisions; with the \-u option, check out but do not lock\&. With neither option, the RCS subdirectories and masters are created but no working copies checked out\&.
.PP
The \-V option displays the program version number and exits\&. \-? displays a help message and exits\&.
.PP
In order to preserve history, D file operations do not delete previously\-created master files; instead, an empty file is checked in as the content and the file\*(Aqs RCS state tag is set to "Deleted"\&. R file operations copy corresponding RCS master files
\fIwithout \fR
deleting the old master file; instead, an empty fiile is checked in as the content and the state set to "Renamed"\&. C operations initialize a new file\&.
.PP
Import\-stream branches are mapped to RCS revision branch structure\&. Each RCS master poduced will include a list of branch tags, each of which has the value of the corresponding RCS branch identifier for that file\&.
.SH "BUGS"
.PP
The following limitations are inherent in the RCS format:
.PP
Annotated tags cannot be preserved in a format readily accessible to RCS\&. This tool deposits them as tagged revisions of a file named
ANNOTATED\-TAGS
in the toplevel RCS directory\&.
.PP
In each commit, the committer date entered in RCS metadata will be the committer date from the import stream, but the committer identity will be lost; all commits are checked in as if by the invoking user and identified with the invoking user\*(Aqs login name\&. (However, this tool preserves complete attribution in comment headers unless the \-p option was selected\&.)
.PP
Lightweight tags and branches may cause errors in older RCS versions, as they are saved with their full (path) names, including slashes\&.
.PP
Submodule links ("M" entries mith mode 160000) and symlinks ("M" entries mith mode 120000) can\*(Aqt be handled; the tool will throw an error if it sees one\&.
.PP
The following are implementation limits of this tool which may be fixed in a future release:
.PP
This tool has not been tested with RCS versions earlier than 5\&.7\&. It is likely older versions will throw errors on some tag and branch names that are legal in fast\-import files\&.
.SH "ERROR RETURNS"
.PP
Returns 1 on any error, 0 otherwise\&.
.SH "AUTHOR"
.PP
Eric S\&. Raymond
esr@thyrsus\&.com; project page at
\m[blue]\fBhttp://www\&.catb\&.org/~esr/rcs\-fast\-import\fR\m[]\&.
